-- Run this SQL in the Supabase SQL Editor to create the required blog table

-- Create the blog table if it doesn't exist
CREATE TABLE IF NOT EXISTS blog (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- Enable Row Level Security (RLS)
ALTER TABLE blog ENABLE ROW LEVEL SECURITY;

-- Create policy for SELECT operations (read access)
CREATE POLICY "Anyone can read blog posts" 
ON blog FOR SELECT 
TO anon
USING (true);

-- Create policy for INSERT operations (write access)
CREATE POLICY "Anyone can create blog posts" 
ON blog FOR INSERT 
TO anon
WITH CHECK (true); 