-- Run this SQL in your Supabase SQL Editor to create the blog table if it doesn't exist
CREATE TABLE IF NOT EXISTS blog (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- Enable Row Level Security (RLS) on the blog table
ALTER TABLE blog ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows anonymous users to insert records
CREATE POLICY "Anonymous users can insert blog posts" 
ON blog FOR INSERT 
TO anon
WITH CHECK (true);

-- Create a policy that allows anonymous users to select records
CREATE POLICY "Anonymous users can select blog posts" 
ON blog FOR SELECT 
TO anon
USING (true); 